<?php

/**
 * BaseActionProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $action_id
 * @property integer $profile_id
 * @property Action $Action
 * @property Profile $Profile
 * 
 * @method integer       getActionId()   Returns the current record's "action_id" value
 * @method integer       getProfileId()  Returns the current record's "profile_id" value
 * @method Action        getAction()     Returns the current record's "Action" value
 * @method Profile       getProfile()    Returns the current record's "Profile" value
 * @method ActionProfile setActionId()   Sets the current record's "action_id" value
 * @method ActionProfile setProfileId()  Sets the current record's "profile_id" value
 * @method ActionProfile setAction()     Sets the current record's "Action" value
 * @method ActionProfile setProfile()    Sets the current record's "Profile" value
 * 
 * @package    std
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActionProfile extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_action_profile');
        $this->hasColumn('action_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));
        $this->hasColumn('profile_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));


        $this->index('i_created_at', array(
             'fields' => 'created_at',
             ));
        $this->index('i_updated_at', array(
             'fields' => 'updated_at',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Action', array(
             'local' => 'action_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}