<?php

/**
 * BaseAction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $route
 * @property string $param
 * @property Doctrine_Collection $Profiles
 * @property Doctrine_Collection $ActionProfile
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getRoute()         Returns the current record's "route" value
 * @method string              getParam()         Returns the current record's "param" value
 * @method Doctrine_Collection getProfiles()      Returns the current record's "Profiles" collection
 * @method Doctrine_Collection getActionProfile() Returns the current record's "ActionProfile" collection
 * @method Action              setId()            Sets the current record's "id" value
 * @method Action              setName()          Sets the current record's "name" value
 * @method Action              setDescription()   Sets the current record's "description" value
 * @method Action              setRoute()         Sets the current record's "route" value
 * @method Action              setParam()         Sets the current record's "param" value
 * @method Action              setProfiles()      Sets the current record's "Profiles" collection
 * @method Action              setActionProfile() Sets the current record's "ActionProfile" collection
 * 
 * @package    std
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAction extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_action');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('route', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             ));
        $this->hasColumn('param', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));


        $this->index('u_param', array(
             'fields' => 
             array(
              0 => 'param',
             ),
             'type' => 'unique',
             ));
        $this->index('i_created_at', array(
             'fields' => 'created_at',
             ));
        $this->index('i_updated_at', array(
             'fields' => 'updated_at',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profile as Profiles', array(
             'refClass' => 'ActionProfile',
             'local' => 'action_id',
             'foreign' => 'profile_id'));

        $this->hasMany('ActionProfile', array(
             'local' => 'id',
             'foreign' => 'action_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}