<?php

/**
 * BaseRepresentative
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $dni
 * @property string $firstname
 * @property string $lastname
 * @property string $description
 * @property string $active
 * @property Doctrine_Collection $Areas
 * @property Doctrine_Collection $Documents
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDni()         Returns the current record's "dni" value
 * @method string              getFirstname()   Returns the current record's "firstname" value
 * @method string              getLastname()    Returns the current record's "lastname" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getActive()      Returns the current record's "active" value
 * @method Doctrine_Collection getAreas()       Returns the current record's "Areas" collection
 * @method Doctrine_Collection getDocuments()   Returns the current record's "Documents" collection
 * @method Representative      setId()          Sets the current record's "id" value
 * @method Representative      setDni()         Sets the current record's "dni" value
 * @method Representative      setFirstname()   Sets the current record's "firstname" value
 * @method Representative      setLastname()    Sets the current record's "lastname" value
 * @method Representative      setDescription() Sets the current record's "description" value
 * @method Representative      setActive()      Sets the current record's "active" value
 * @method Representative      setAreas()       Sets the current record's "Areas" collection
 * @method Representative      setDocuments()   Sets the current record's "Documents" collection
 * 
 * @package    std
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRepresentative extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_representative');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('dni', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('firstname', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             ));
        $this->hasColumn('lastname', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             'notnull' => false,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('i_firstname', array(
             'fields' => 
             array(
              0 => 'firstname',
             ),
             ));
        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Area as Areas', array(
             'local' => 'id',
             'foreign' => 'representative_id'));

        $this->hasMany('Document as Documents', array(
             'local' => 'id',
             'foreign' => 'representative_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'firstname',
              1 => 'lastname',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}