<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Actions
 * @property Doctrine_Collection $ActionProfile
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method Doctrine_Collection getUsers()         Returns the current record's "Users" collection
 * @method Doctrine_Collection getActions()       Returns the current record's "Actions" collection
 * @method Doctrine_Collection getActionProfile() Returns the current record's "ActionProfile" collection
 * @method Profile             setId()            Sets the current record's "id" value
 * @method Profile             setName()          Sets the current record's "name" value
 * @method Profile             setDescription()   Sets the current record's "description" value
 * @method Profile             setUsers()         Sets the current record's "Users" collection
 * @method Profile             setActions()       Sets the current record's "Actions" collection
 * @method Profile             setActionProfile() Sets the current record's "ActionProfile" collection
 * 
 * @package    std
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_profile');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('u_name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->index('i_created_at', array(
             'fields' => 'created_at',
             ));
        $this->index('i_updated_at', array(
             'fields' => 'updated_at',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as Users', array(
             'local' => 'id',
             'foreign' => 'profile_id'));

        $this->hasMany('Action as Actions', array(
             'refClass' => 'ActionProfile',
             'local' => 'profile_id',
             'foreign' => 'action_id'));

        $this->hasMany('ActionProfile', array(
             'local' => 'id',
             'foreign' => 'profile_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}