<?php

/**
 * ActionProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionProfileTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActionProfile');
    }
}