<?php

/**
 * Area
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    std
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Area extends BaseArea
{
  public function getActiveStr()
  {
  	$actives = $this->getTable()->getStatuss();
  	return $actives[$this->getActive()];
  }
  
  public function save(Doctrine_Connection $conn = null)
  {
    if($this->isNew())
    {
    	$this->setNewRank();
    }
    
    parent::save($conn);
  }
  
  public function getRepresentativeName()
  {
      return $this->getRepresentative();
  }
  
  
  public function setNewRank()
  {
  	$rank = $this->getTable()->getNewRank();
  	$this->setRank($rank);
  }
  
  public function getFormattedDatetime($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getCreatedAt(), $format);
  }

}