<?php

/**
 * Document
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    std
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Document extends BaseDocument
{
    
  public function generatePathFilename($file)
  {
    return Stringkit::fixFilename($file->getOriginalName()).'_'.rand(11111, 99999).$file->getOriginalExtension();
  }

  
  public function getDocumentClassName()
  {
      return $this->getDocumentClass()->getName();
  }
  
  public function getRepresentativeName()
  {
      return $this->getRepresentative();
  }
  
  public function getRegistrationTypeName()
  {
    $actives = $this->getTable()->getRegistrationType();
    return $actives[$this->getRegistrationType()];
  }  
  
  public function getDocumentDate()
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->_get('document_date'), 'd');
  }
}