<?php

/**
 * DocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Document');
    }
    
  const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0,
    TYPE_CONSULTA = 1,
    TYPE_CAPACITACION = 2,
    TYPE_CITACIONES = 3,
    TYPE_CONTRATOS = 4,
    TYPE_CONOCIMIENTO = 5,
    TYPE_NOTIFICACION = 6,
    TYPE_PLAN_DE_TRABAJO = 7,
    TYPE_VIATICOS_MOVILIDAD_PASAJES = 8;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si',
                               self::STATUS_INACTIVE   => 'No',
                             );
  
  protected static
    $registration_type     = array
                             (
                               self::TYPE_CONSULTA     => 'Consultas'  ,
                               self::TYPE_CAPACITACION => 'Capacitación',
                               self::TYPE_CITACIONES   => 'Citaciones',
                               self::TYPE_CONTRATOS    => 'Contratos',
                               self::TYPE_CONOCIMIENTO => 'Conocimiento',
                               self::TYPE_NOTIFICACION => 'Notificación',
                               self::TYPE_PLAN_DE_TRABAJO   => 'Plan de Trabajo',
                               self::TYPE_VIATICOS_MOVILIDAD_PASAJES   => 'Viaticos, movilidad, pasajes',
                             );  
  
  public function getStatuss()
  {
    return self::$status;
  }
  
  public function getRegistrationType()
  {
    return self::$registration_type;  
  }
  
  public function getPathDir()
  {
    return sfConfig::get('app_document_path_dir');
  }
  
  public function getPathPath()
  {
    return sfConfig::get('app_document_path_path');
  }
  
  public function updateQueryForList(DoctrineQuery $q, $params)
  {
       
           
      if($params['from'] <> '0' and $params['to'] <> '0')
      {
        $q->andIntervalWhere('d.created_at',$params['from'], $params['to']);    
      }

    if($params['document_class'])
    {
   
          $q->andWhere('d.document_class_id = ?', $params['document_class']);
    }
    
    if($params['area'])
    {
   
          $q->andWhere('d.area_id = ?', $params['area']);
    }
    
  //  $area_id = sfContext::getInstance()->getUser()->getAreaId();
    
  //  $q->andWhere('d.area_id = ?', array($area_id));
    
    return $q;
  }  
    
}