<?php

/**
 * Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    std
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Profile extends BaseProfile
{
  public function hasAction($action)
  {
    $actionProfiles = $this->getActionProfiles();
    foreach ($actionProfiles as $actionProfile)
    {
      if ($actionProfile->getActionId() == $action->getId())
      {
        return true;
      }
    }
    
    return false;
  }
  
  public function getActionName()
  {
      $return = '';
      foreach ($this->getActions() as $action)
      {
          $return .=sprintf('%s<br/>',$action->getName());
      }
      return $return;
  }  
  
  public function __toString()
  {
    return $this->getName();
  }

}