<?php

/**
 * ProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profile');
    }
  public function getQueryForList(DoctrineQuery  $q)
  {
    $query = DoctrineQuery::create()
             ->select('COUNT(ap.action_id)')
             ->from('ActionProfile ap')
             ->where('ap.profile_id = p.id');
          
    $q->addSelect('p.* , ('.$query->getDql().') actions_number');    
  }

}