<?php

/**
 * RecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecordTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Record');
    }
}