<?php

/**
 * RecordLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecordLogTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecordLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RecordLog');
    }
}