<?php

/**
 * RecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecordTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Record');
    }
    
  const
    STATUS_PENDING     = 1,
    STATUS_RECEIVED    = 2,
    STATUS_DERIVED     = 3,
    STATUS_RETURNED    = 4,
    STATUS_COMPLETED   = 5;
  
  
  protected static
    $status                = array
                             (
                               self::STATUS_PENDING     => 'Pendiente',
                               self::STATUS_RECEIVED    => 'Recibido',
                               self::STATUS_DERIVED     => 'Derivado',
                               self::STATUS_RETURNED    => 'Devuelto',
                               self::STATUS_COMPLETED   => 'Completado',
                             );
  
  protected static
    $color                = array(
    self::STATUS_PENDING     => 'purple',
    self::STATUS_RECEIVED    => 'orange',
    self::STATUS_DERIVED     => 'skyblue',
    self::STATUS_RETURNED    => 'red',
    self::STATUS_COMPLETED   => 'green');  
  
  
  public function getStatuss()
  {
    return self::$status;
  }
  
  public function getColors()
  {
    return self::$color;
  }  
  public function findNextCode()
  {
    $q = $this->createAliasQuery();
    
    $qty = $q->count();
    $code   = $qty+1;
    
    return str_pad($code, 8, '0', STR_PAD_LEFT);
  }
  
  public function getOtherAreas($area_id)
  {
  	 $q = Doctrine_Query::create()
              ->select('*')
              ->from('Area a');
             
         if($area_id <> null)
         {
           $q->where('a.id <> ?', $area_id);
         }
             
  	 return $q;
  } 
  
   public function updateQueryForList(DoctrineQuery $q, array $params)
  {
       $q->addSelect("r.*, CONCAT(u.first_name,' ', u.last_name) user_name, fa.name from_area_name, ta.name to_area_name")
      ->leftJoin('r.FromArea fa')
      ->leftJoin('r.ToArea ta')
      ->leftJoin('r.User u')
      ->andIntervalWhere('r.created_at',$params['from'], $params['to']);
    if($params['status'])
    {
      $q->addWhere('r.status = ?', $params['status']);    
    }
    $area_id = sfContext::getInstance()->getUser()->getAreaId();
    $q->andWhere('r.from_area_id = ?', $area_id)->orWhere('r.to_area_id = ?', $area_id);
    
    
    
    
    return $q;
  }

}