<?php

/**
 * Record
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    std
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Record extends BaseRecord
{
  public function getStatusStr()
  {
    $actives = $this->getTable()->getStatuss();
    return $actives[$this->getStatus()];
  }
  
  public function getAreaName()
  {
      return $this->getFromArea()->getName();
  }
  

  
  public function getFormattedDatetime($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getCreatedAt(), $format);
  }
}