<?php

/**
 * RepresentativeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RepresentativeTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object RepresentativeTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Representative');
  }
    
  const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si'  ,
                               self::STATUS_INACTIVE   => 'No',
                             );
                             
  public function getStatuss()
  {
    return self::$status;
  }	
    
}